train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../Data/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../Data/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 16
  
Im_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ../Data/benchmark/ImTest/LR_bicubic/X4
      root_path_2: ../Data/benchmark/ImTest/HR
  wrapper:
    name: sr-implicit-paired
    args: {}
  batch_size: 1
eval_type: benchmark-4
  
data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: lte_eq
  args:
    encoder_spec:
      name: edsr-eq-baseline
      args:
        no_upsampling: true
        kernel_size: 5
        res_scale: 0.1
    imnet_spec:
      name: e_mlp_lte
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    hidden_dim: 256
    tranNum: 4
    kernel_size: 5


optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100

