  
Im_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./exampleImage/LR_bicubic/X4
      root_path_2: ./exampleImage/HR
  wrapper:
    name: sr-implicit-paired
    args: {}
  batch_size: 1
eval_type: benchmark-4

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif_old
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        n_resblocks: 4
        n_feats: 256
        kernel_size: 7
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]
    local_ensemble: false

        

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
contrast_rito: 8
