Im_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./exampleImage/LR_bicubic/X4
      root_path_2: ./exampleImage/HR
  wrapper:
    name: sr-implicit-paired
    args: {}
  batch_size: 1
eval_type: benchmark-4

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: lte_eq
  args:
    encoder_spec:
      name: swinir_eq
      args:
        no_upsampling: true
    imnet_spec:
      name: e_mlp_lte
      args: 
        out_dim: 3
        hidden_list: [256, 256, 256]
    kernel_size: 3
    tranNum: 4
    hidden_dim: 256
    local_ensemble: false
    upinput: false
    corrd_scale: 0.1

window_size: 8
optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
contrast_rito: 8